/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vmapi4java */

#ifndef _Included_vmapi4java
#define _Included_vmapi4java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vmapi4java
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vmapi4java_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
