/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VMMain */

#ifndef _Included_VMMain
#define _Included_VMMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VMMain
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VMMain_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     VMMain
 * Method:    get_code
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_VMMain_get_1code
  (JNIEnv *, jobject, jlong);

/*
 * Class:     VMMain
 * Method:    is_account
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_VMMain_is_1account
  (JNIEnv *, jobject, jlong);

/*
 * Class:     VMMain
 * Method:    s2n
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_VMMain_s2n
  (JNIEnv *, jobject, jstring);

/*
 * Class:     VMMain
 * Method:    n2s
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_VMMain_n2s
  (JNIEnv *, jobject, jlong);

/*
 * Class:     VMMain
 * Method:    action_data_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_VMMain_action_1data_1size
  (JNIEnv *, jobject);

/*
 * Class:     VMMain
 * Method:    read_action_data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_VMMain_read_1action_1data
  (JNIEnv *, jobject);

/*
 * Class:     VMMain
 * Method:    require_recipient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_VMMain_require_1recipient
  (JNIEnv *, jobject, jlong);

/*
 * Class:     VMMain
 * Method:    require_auth
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_VMMain_require_1auth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     VMMain
 * Method:    db_store_i64
 * Signature: (JJJJ[B)I
 */
JNIEXPORT jint JNICALL Java_VMMain_db_1store_1i64
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray);

/*
 * Class:     VMMain
 * Method:    db_update_i64
 * Signature: (IJ[B)V
 */
JNIEXPORT void JNICALL Java_VMMain_db_1update_1i64
  (JNIEnv *, jobject, jint, jlong, jbyteArray);

/*
 * Class:     VMMain
 * Method:    db_remove_i64
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_VMMain_db_1remove_1i64
  (JNIEnv *, jobject, jint);

/*
 * Class:     VMMain
 * Method:    db_get_i64
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_VMMain_db_1get_1i64
  (JNIEnv *, jobject, jint);

/*
 * Class:     VMMain
 * Method:    db_next_i64
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_VMMain_db_1next_1i64
  (JNIEnv *, jobject, jint);

/*
 * Class:     VMMain
 * Method:    db_previous_i64
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_VMMain_db_1previous_1i64
  (JNIEnv *, jobject, jint);

/*
 * Class:     VMMain
 * Method:    db_find_i64
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_VMMain_db_1find_1i64
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     VMMain
 * Method:    db_lowerbound_i64
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_VMMain_db_1lowerbound_1i64
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     VMMain
 * Method:    db_upperbound_i64
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_VMMain_db_1upperbound_1i64
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     VMMain
 * Method:    db_end_i64
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_VMMain_db_1end_1i64
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
