/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RpcService_CONSTANTS_H
#define RpcService_CONSTANTS_H

#include "../../ipc_server/thrift/RpcService_types.h"

namespace cpp {

class RpcServiceConstants {
 public:
  RpcServiceConstants();

};

extern const RpcServiceConstants g_RpcService_constants;

} // namespace

#endif
