/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "../../ipc_server/thrift/RpcService_constants.h"

namespace cpp {

const RpcServiceConstants g_RpcService_constants;

RpcServiceConstants::RpcServiceConstants() {
}

} // namespace

